const A = 'assets/';

const pageNames = {
  services: 'Services', curtains: 'Curtains & Blinds', wardrobes: 'Wardrobes & Storage', kitchens: 'Modular Kitchens',
  'full-home': 'Full Home Interiors & Renovation', 'other-services': 'Other Home Services', materials: 'Materials & Finishes',
  'plan-home': 'Plan Your Home', 'curtains-planner': 'Curtains & Blinds Planner', 'wardrobe-planner': 'Wardrobe Planner',
  'project-planner': 'Home Project Planner', estimate: 'Your Plan & Estimate', commitment: 'Our Service Commitment', journey: 'How We Work',
  projects: 'Projects & Client Stories', 'project-story': 'Individual Project Story', advice: 'Home Advice & Guides', guide: 'Damp Walls Guide',
  'article-curtains': 'Curtains or Blinds Guide', 'article-privacy': 'Privacy and Natural Light Guide', 'article-small-wardrobes': 'Small Bedroom Wardrobe Guide',
  'article-hinged-sliding': 'Hinged or Sliding Wardrobe Guide', 'article-quotation': 'Interior Quotation Guide', 'article-advance': 'Installer Advance Guide',
  about: 'About AK Interiors', faqs: 'Frequently Asked Questions', 'start-project': 'Start Your Project', received: 'Enquiry Received',
  contact: 'Contact & Service Areas', privacy: 'Privacy Policy', terms: 'Terms & Consultation Policy', dashboard: 'Enquiry Dashboard', detail: 'Enquiry Detail'
};

const header = () => `
  <header class="site-header">
    <a class="brand" href="index.html"><span class="brand-mark">AK<span>✦</span></span><span class="brand-copy"><strong>AK INTERIORS</strong><small>Designing Dream Spaces</small></span></a>
    <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="primary-nav">Menu</button>
    <nav id="primary-nav" class="main-nav" aria-label="Primary navigation">
      <a href="services.html">Services</a><a href="plan-your-home.html">Plan Your Home</a><a href="service-commitment.html">Our Commitment</a><a href="projects.html">Projects</a><a href="home-advice.html">Home Advice</a>
    </nav>
    <a class="button button-small header-cta" href="start-project.html">Start Your Project <span>→</span></a>
  </header>`;

const footer = () => `
  <footer class="site-footer">
    <a class="brand footer-brand" href="index.html"><span class="brand-mark">AK<span>✦</span></span><span class="brand-copy"><strong>AK INTERIORS</strong><small>Designing Dream Spaces</small></span></a>
    <nav aria-label="Footer navigation"><a href="contact.html">Contact</a><span>|</span><a href="faqs.html">FAQs</a><span>|</span><a href="privacy.html">Privacy</a></nav>
    <p>Website Strategy, Design &amp; Development by <strong>Tivoro</strong></p>
  </footer>`;

const shell = content => `${header()}<main class="inner-page">${content}</main>${footer()}`;
const hero = ({eyebrow,title,copy,image=A+'hero-living-room.png'}) => `<section class="inner-hero"><img src="${image}" alt=""/><div class="container"><div class="inner-hero-copy"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${copy}</p></div></div></section>`;
const cta = (title='Ready to begin?',copy='Tell us about your home and we’ll help you plan the next step.') => `<section class="page-section"><div class="container"><div class="page-cta"><div><h2>${title}</h2><p>${copy}</p></div><a class="button button-light" href="start-project.html">Start Your Project →</a></div></div></section>`;
const imgCard = (img,title,copy,href='#',link='Explore') => `<article class="content-card"><img src="${img}" alt="${title}"/><div class="content-card-body"><h3>${title}</h3><p>${copy}</p><a href="${href}">${link} →</a></div></article>`;
const options = items => `<div class="option-grid">${items.map(([img,title,copy])=>`<article class="option-card"><img src="${img}" alt="${title}"/><h3>${title}</h3><p>${copy}</p></article>`).join('')}</div>`;

const serviceConfig = {
  curtains:{eyebrow:'Curtains & Blinds',title:'Control Light.<br>Create Ambience.<br>Enhance Privacy.',copy:'A wide range of curtains and blinds to suit your style, space and lifestyle.',image:A+'curtains-room.png',section:'Compare popular options',items:[['Sheer curtains','Soft daylight and privacy'],['Blackout curtains','Restful rooms and light control'],['Roller blinds','Clean and practical'],['Roman blinds','Tailored and premium']]},
  wardrobes:{eyebrow:'Wardrobes & Storage',title:'Organised Living<br>for Everyday Life',copy:'Thoughtfully designed wardrobes and storage solutions that make the most of your space.',image:A+'wardrobe-room.png',section:'Popular storage layouts',items:[['Hinged wardrobes','Classic and timeless'],['Sliding wardrobes','Space-saving design'],['Walk-in storage','Flexible organisation'],['Specialised storage','Purpose-built solutions']]},
  kitchens:{eyebrow:'Modular Kitchens',title:'A Kitchen<br>for Real Life',copy:'Designed for your cooking style, space and storage needs.',image:A+'full-home-room.png',section:'Choose a layout',items:[['L-shape kitchen','Efficient use of space'],['U-shape kitchen','Maximum storage'],['Straight kitchen','Simple and efficient'],['Island kitchen','Social and spacious']]},
  'full-home':{eyebrow:'Full Home Interiors & Renovation',title:'A More Beautiful<br>Way to Live',copy:'End-to-end design and execution for new homes and home renovations.',image:A+'full-home-room.png',section:'Typically included',items:[['Space planning','Thoughtful layouts for daily life'],['Modular furniture','Coordinated kitchen and storage'],['Lighting & ceilings','Balanced ambience'],['On-site supervision','A coordinated execution']]},
  'other-services':{eyebrow:'Other Home Services',title:'Complete Your Home<br>with Expert Solutions',copy:'From doors and furniture to flooring, ceilings and lighting, we help you bring every detail together.',image:A+'hero-living-room.png',section:'Explore home services',items:[['Doors','Stylish and durable'],['Furniture','Custom and ready furniture'],['Flooring','Warm and practical finishes'],['Ceilings & lighting','The right ambience']]},
  materials:{eyebrow:'Materials & Finishes',title:'Beautiful Surfaces.<br>Lasting Homes.',copy:'A curated range of materials and finishes to suit your style, performance needs and everyday living.',image:A+'wardrobe-room.png',section:'Explore popular materials',items:[['Laminates','Durable and versatile'],['Veneers','Natural wood beauty'],['Acrylic','Modern and sleek'],['Tiles & flooring','Practical, lasting finishes']]}
};

function servicesOverview(){
  const cards=[
    [A+'curtains-room.png','Curtains & Blinds','Light control, privacy and style for every home.','curtains-blinds.html'],
    [A+'wardrobe-room.png','Wardrobes & Storage','Smart storage for organised living.','wardrobes-storage.html'],
    [A+'full-home-room.png','Modular Kitchens','Functional, elegant and built for everyday life.','modular-kitchens.html'],
    [A+'full-home-room.png','Full Home Interiors','End-to-end design and execution.','full-home-interiors.html'],
    [A+'hero-living-room.png','Other Home Services','Doors, furniture, flooring, ceilings and more.','other-home-services.html'],
    [A+'wardrobe-room.png','Materials & Finishes','Curated finishes for a beautiful and durable home.','materials-finishes.html']
  ];
  return shell(hero({eyebrow:'Our Services',title:'Beautiful Homes<br>Built Around You',copy:'From single spaces to complete homes, we design and create interiors that are functional, elegant and lasting.',image:A+'hero-living-room.png'})+`<section class="page-section"><div class="container"><h2>Choose a Service</h2><p class="section-intro">Explore our interior services and find the right solution for your home.</p><div class="content-grid">${cards.map(c=>imgCard(...c,'Explore Service')).join('')}</div></div></section>`+cta());
}

function servicePage(key){ const c=serviceConfig[key]; return shell(hero(c)+`<section class="page-section"><div class="container"><div class="feature-row"><article><span class="line-icon">◉</span><h3>Thoughtful Design</h3><p>Solutions shaped around your space and daily life.</p></article><article><span class="line-icon">◇</span><h3>Clear Material Choices</h3><p>Compare practical options before you decide.</p></article><article><span class="line-icon">✓</span><h3>Coordinated Installation</h3><p>Planning and execution with clear checks.</p></article></div></div></section><section class="page-section tint"><div class="container"><h2>${c.section}</h2><p class="section-intro">Understand the possibilities before you start planning.</p>${options(c.items.map((x,i)=>[i%2?c.image:A+'curtains-room.png',x[0],x[1]]))}</div></section>`+cta('Plan your space with confidence.','Share your requirements and we’ll help you choose the right next step.'));
}

function planHome(){ return shell(hero({eyebrow:'Plan Your Home',title:'Take the First Step<br>Towards Your Dream Home',copy:'Use our guided tools to understand your needs and create a more personalised experience.',image:A+'hero-living-room.png'})+`<section class="page-section"><div class="container"><h2>Choose a Tool</h2><p class="section-intro">Start with the space you want to improve.</p><div class="content-grid">${imgCard(A+'curtains-room.png','Curtains & Blinds Planner','Find the right style and light control.','curtains-planner.html','Start Planner')}${imgCard(A+'wardrobe-room.png','Wardrobe Planner','Plan your wardrobe and storage needs.','wardrobe-planner.html','Start Planner')}${imgCard(A+'full-home-room.png','Home Project Planner','Share your full-home requirements.','home-project-planner.html','Start Planner')}</div></div></section><section class="page-section tint"><div class="container"><h2>What You Need</h2><div class="feature-row"><article><span class="line-icon">1</span><h3>Photos</h3><p>Share current photos of your space.</p></article><article><span class="line-icon">2</span><h3>Approximate Dimensions</h3><p>Approximate room size or key wall dimensions.</p></article><article><span class="line-icon">3</span><h3>Budget</h3><p>Your preferred range, where known.</p></article></div></div></section>`); }

const stepper=(labels,active=0)=>`<ol class="full-stepper">${labels.map((x,i)=>`<li class="${i===active?'active':''}"><span>${i+1}</span>${x}</li>`).join('')}</ol>`;
const field=(label,control)=>`<label class="field">${label}${control}</label>`;

function curtainsPlanner(){ return plannerShell(10,'Curtains & Blinds Planner',stepper(['Room','Measurements','Preferences','Budget'])+`<div class="planner-content"><div class="form-stack">${field('Select Room','<select><option>Living Room</option><option>Bedroom</option><option>Dining Room</option></select>')}<div><strong>Window Type</strong><div class="choice-grid"><label class="choice"><input type="radio" name="window" checked/> Standard</label><label class="choice"><input type="radio" name="window"/> Bay Window</label><label class="choice"><input type="radio" name="window"/> Corner Window</label></div></div>${field('Privacy Level','<input type="range" min="1" max="3" value="2"/>')}<div><strong>Light Control</strong><div class="choice-grid"><label class="choice"><input type="radio" name="light"/> Sheer</label><label class="choice"><input type="radio" name="light" checked/> Filter</label><label class="choice"><input type="radio" name="light"/> Block</label></div></div></div><div><img src="${A}curtains-room.png" alt="Curtain planning preview" style="width:100%;height:350px;object-fit:cover;border-radius:10px"/><div class="form-grid" style="margin-top:15px">${field('Width (cm)','<input value="300"/>')}${field('Height (cm)','<input value="240"/>')}</div></div></div>`,'your-plan-estimate.html','Next: Preferences'); }

function wardrobePlanner(){ return plannerShell(11,'Wardrobe Planner',stepper(['Configuration','Dimensions','Storage','Finish','Budget'])+`<div class="planner-content"><div><strong>Wardrobe Type</strong><div class="choice-grid"><label class="choice visual-choice"><input type="radio" name="type" checked/><img src="${A}wardrobe-room.png" alt="Hinged wardrobe"/><strong>Hinged Doors</strong></label><label class="choice visual-choice"><input type="radio" name="type"/><img src="${A}wardrobe-room.png" alt="Sliding wardrobe"/><strong>Sliding Doors</strong></label></div><h3>Storage Options</h3><div class="choice-grid"><label class="choice"><input type="checkbox" checked/> Hanging Rails</label><label class="choice"><input type="checkbox"/> Shoe Storage</label><label class="choice"><input type="checkbox" checked/> Shelves</label><label class="choice"><input type="checkbox" checked/> Drawers</label></div></div><div><img src="${A}wardrobe-room.png" alt="Wardrobe preview" style="width:100%;height:300px;object-fit:cover;border-radius:10px"/><div class="form-grid" style="margin-top:15px">${field('Width (cm)','<input value="240"/>')}${field('Height (cm)','<input value="240"/>')}${field('Depth (cm)','<input value="60"/>')}${field('Finish / Colour','<select><option>Light Oak</option><option>Walnut</option><option>Ivory</option></select>')}</div></div></div>`,'your-plan-estimate.html','Next: Budget'); }

function projectPlanner(){ return plannerShell(12,'Home Project Planner',stepper(['Services','Property','Timing','Review'])+`<div class="planner-content"><div><strong>Select Service(s)</strong><div class="choice-grid"><label class="choice"><input type="checkbox" checked/> Curtains & Blinds</label><label class="choice"><input type="checkbox" checked/> Wardrobes</label><label class="choice"><input type="checkbox"/> Flooring</label><label class="choice"><input type="checkbox"/> Painting</label><label class="choice"><input type="checkbox"/> Carpentry</label><label class="choice"><input type="checkbox"/> Lighting</label></div><div class="form-grid" style="margin-top:18px">${field('Number of Rooms','<input type="number" min="1" value="3"/>')}${field('Property Location','<input value="Kangra"/>')}${field('Property Type','<select><option>Independent home</option><option>Apartment</option></select>')}${field('Preferred Timing','<select><option>Within 3 months</option><option>3–6 months</option><option>Flexible</option></select>')}</div></div><div>${field('Upload Photos (optional)','<div class="upload-box">⇧<br/>Drag and drop photos here<br/>or click to upload</div>')}<div class="photo-strip" style="margin-top:12px"><img src="${A}curtains-room.png" alt="Room"/><img src="${A}wardrobe-room.png" alt="Room"/><img src="${A}full-home-room.png" alt="Room"/></div></div></div>`,'your-plan-estimate.html','Next: Review Your Plan'); }

function plannerShell(no,title,content,next,label){ return shell(`<section class="planner-page"><div class="container"><div class="planner-page-title"><span class="number-badge">${no}</span><h1>${title}</h1></div><div class="planner-panel">${content}<div class="planner-actions"><a class="button secondary" href="plan-your-home.html">← Back</a><a class="button" href="${next}">${label} →</a></div></div></div></section>`); }

function estimate(){ return shell(`<section class="planner-page"><div class="container"><div class="planner-page-title"><span class="number-badge">13</span><h1>Your Plan &amp; Estimate</h1></div><div class="planner-panel"><h2>Summary of Your Selections</h2><div class="summary-grid">${summary(A+'curtains-room.png','Curtains & Blinds','Living room','Standard window')}${summary(A+'wardrobe-room.png','Wardrobe','Hinged doors','Light oak')}${summary(A+'full-home-room.png','Home Project','3 rooms','Kangra')}</div><div class="notice"><strong>Estimated Cost</strong><br/>Indicative range available after review. We will provide a detailed quotation after understanding your requirements and site conditions.</div><div class="split-notes"><div><h3>✓ Inclusions (typical)</h3><ul><li>Supply of selected materials</li><li>Installation workmanship</li><li>Disposal of packaging</li></ul></div><div class="negative"><h3>✕ Exclusions (typical)</h3><ul><li>Structural works</li><li>Electrical and plumbing works</li><li>Special permits or approvals</li></ul></div></div><div class="planner-actions"><a class="button secondary" href="plan-your-home.html">← Back</a><a class="button" href="start-project.html">Submit for Review →</a></div></div></div></section>`); }
const summary=(img,title,a,b)=>`<article class="summary-card"><img src="${img}" alt="${title}"/><h3>${title}</h3><dl><dt>Selection</dt><dd>${a}</dd><dt>Preference</dt><dd>${b}</dd></dl></article>`;

function commitment(){ const cards=[['▤','Proposed Written Scope','A clear and itemised scope of works based on your requirements.'],['◇','Approved Materials','Only materials and brands agreed in the quotation will be used.'],['□','Agreed Timelines','A mutually agreed schedule with realistic timelines.'],['✓','Change Approval','Any changes require your prior approval in writing.'],['⌂','Installation Checks','Quality checks throughout installation.'],['◉','After-sales Support','We remain available after completion.']]; return shell(hero({eyebrow:'Our Service Commitment',title:'Good interiors.<br>Clear commitments.',copy:'Know what you can expect before your project begins.',image:A+'full-home-room.png'})+`<section class="page-section"><div class="container"><h2>What You Can Expect</h2><div class="content-grid">${cards.map(x=>`<article class="content-card"><div class="content-card-body"><span class="line-icon">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></div></article>`).join('')}</div><div class="notice">Final commitments will be confirmed in your written quotation.</div></div></section>`+cta()); }

function journey(){ const steps=['Plan online','Discuss remotely','Review suitability','Site measurement','Written quotation','Approval','Execute','Handover']; return shell(hero({eyebrow:'How We Work',title:'Your Project Journey',copy:'A clear path from your first plan to final handover.',image:A+'hero-living-room.png'})+`<section class="page-section"><div class="container"><div class="journey">${steps.map((x,i)=>`<article class="journey-step"><span class="step-no">${i+1}</span><strong>${x}</strong><p>${['Tell us about your home and select the services you need.','We discuss your needs and answer questions.','We review your requirements, photos and information.','We visit to take accurate measurements and confirm details.','You receive a clear and itemised quotation.','You confirm the scope and approve the quotation.','Our team completes the agreed work.','We carry out final checks and hand over your completed project.'][i]}</p></article>`).join('')}</div></div></section>`); }

const projectStories = {
  'living-room-curtains': {
    category:'curtains', cardImage:A+'curtains-room.png', cardTitle:'Living room curtains',
    eyebrow:'Projects · Living room curtains', title:'Soft light and privacy<br>for everyday living',
    copy:'An illustrative living-room project using layered curtains to balance daylight, privacy and warmth.',
    heroImage:A+'curtains-room.png', beforeImage:A+'project-curtains-before.png', afterImage:A+'curtains-room.png',
    beforeAlt:'Living room before layered curtains', afterAlt:'Living room with finished layered curtains',
    problem:'Strong daylight and an exposed window made the living room feel less comfortable at different times of day.',
    approach:'We planned a light sheer layer for daytime softness with fuller curtains for privacy and evening comfort.',
    materials:'Ceiling-height sheers, lined curtains, coordinated tracks and warm neutral fabrics.',
    result:'A brighter, softer living room with flexible privacy and a finish that complements the furniture.'
  },
  'bedroom-fitted-storage': {
    category:'wardrobes', cardImage:A+'wardrobe-room.png', cardTitle:'Bedroom with fitted storage',
    eyebrow:'Projects · Bedroom with fitted storage', title:'A calmer, more<br>organised bedroom',
    copy:'An illustrative project showing how thoughtful storage can change the way a bedroom feels.',
    heroImage:A+'wardrobe-room.png', beforeImage:A+'project-wardrobe-before.png', afterImage:A+'wardrobe-room.png',
    beforeAlt:'Bedroom before fitted storage planning', afterAlt:'Bedroom with finished fitted wardrobes',
    problem:'Limited storage left everyday belongings visible and made the bedroom feel busy rather than restful.',
    approach:'We planned a fitted wardrobe around clothing, luggage and daily-access needs while keeping circulation clear.',
    materials:'Warm timber interiors, soft neutral shutters, discreet handles and durable wardrobe hardware.',
    result:'A calm, organised bedroom with practical storage and a clean, cohesive appearance.'
  },
  'dining-room-blinds': {
    category:'curtains', cardImage:A+'project-blinds-after.png', cardTitle:'Living room blinds',
    eyebrow:'Projects · Living room blinds', title:'Comfortable daylight<br>throughout the day',
    copy:'An illustrative project using tailored Roman blinds to control glare while keeping the room open and bright.',
    heroImage:A+'project-blinds-after.png', beforeImage:A+'project-curtains-before.png', afterImage:A+'project-blinds-after.png',
    beforeAlt:'Living room windows before blinds were installed', afterAlt:'The same living room with tailored Roman blinds',
    problem:'Direct sunlight created glare and heat in the living room during the brightest hours.',
    approach:'We selected an adjustable blind solution that could soften sunlight without closing off the view.',
    materials:'Made-to-measure blinds, colour-matched headrail and easy-clean light-filtering fabric.',
    result:'A more comfortable living area with practical light control and a restrained finish.'
  },
  'feature-wall-restoration': {
    category:'full-home', cardImage:A+'damp-wall.png', cardTitle:'Feature wall restoration',
    eyebrow:'Projects · Feature wall restoration', title:'A healthy wall with<br>a considered finish',
    copy:'An illustrative restoration showing why the source of moisture should be addressed before decorating.',
    heroImage:A+'damp-wall.png', beforeImage:A+'damp-wall.png', afterImage:A+'project-wall-after.png',
    beforeAlt:'Feature wall showing visible damp damage', afterAlt:'Restored interior wall with a clean decorative finish',
    problem:'Recurring damp marks and peeling paint prevented the room from feeling finished and well maintained.',
    approach:'The moisture source was reviewed first, followed by drying, surface preparation and a suitable final treatment.',
    materials:'Repair compound, moisture-appropriate primer and a durable decorative wall finish.',
    result:'A clean, stable feature wall prepared for long-term use rather than a short cosmetic cover-up.'
  },
  'fitted-wardrobe-storage': {
    category:'wardrobes', cardImage:A+'wardrobe-room.png', cardTitle:'Fitted wardrobe storage',
    eyebrow:'Projects · Fitted wardrobe storage', title:'Storage planned around<br>real daily routines',
    copy:'An illustrative wardrobe project that turns a full wall into useful, easy-to-maintain storage.',
    heroImage:A+'wardrobe-room.png', beforeImage:A+'project-wardrobe-before.png', afterImage:A+'wardrobe-room.png',
    beforeAlt:'Room wall before fitted wardrobe installation', afterAlt:'Full-wall fitted wardrobe with organised storage',
    problem:'Freestanding storage used the wall inefficiently and did not provide enough space for clothes and accessories.',
    approach:'We divided the wardrobe into hanging, folded, drawer and overhead zones based on everyday use.',
    materials:'Custom cabinetry, soft-close hardware, internal drawers and a warm neutral laminate finish.',
    result:'More usable storage, easier organisation and a built-in appearance that makes the room feel quieter.'
  },
  'coordinated-home-interior': {
    category:'full-home', cardImage:A+'full-home-room.png', cardTitle:'Coordinated home interior',
    eyebrow:'Projects · Coordinated home interior', title:'One clear language<br>across the whole home',
    copy:'An illustrative full-home project connecting living, dining and storage spaces through consistent details.',
    heroImage:A+'full-home-room.png', beforeImage:A+'project-full-home-before.png', afterImage:A+'full-home-room.png',
    beforeAlt:'Home interior before coordinated design work', afterAlt:'Completed open-plan home interior',
    problem:'Individual rooms felt disconnected because colours, lighting and furniture finishes had been chosen separately.',
    approach:'We created a shared palette and repeated key materials while adapting each room to its own function.',
    materials:'Warm wood finishes, layered lighting, neutral upholstery and coordinated storage details.',
    result:'A cohesive home where each room has its own purpose while still feeling part of the same design.'
  }
};

function projects(){ const ps=Object.entries(projectStories); return shell(hero({eyebrow:'Projects & Client Stories',title:'Real homes.<br>Thoughtful solutions.',copy:'Explore recent work and find ideas for your home.',image:A+'full-home-room.png'})+`<section class="page-section"><div class="container"><div class="project-filters" aria-label="Filter projects"><button class="pill active" type="button" data-filter="all" aria-pressed="true">All</button><button class="pill" type="button" data-filter="curtains" aria-pressed="false">Curtains & Blinds</button><button class="pill" type="button" data-filter="wardrobes" aria-pressed="false">Wardrobes & Storage</button><button class="pill" type="button" data-filter="full-home" aria-pressed="false">Full Home</button></div><div class="project-grid" aria-live="polite">${ps.map(([slug,p])=>`<article class="project-card" data-category="${p.category}"><a class="project-card-link" href="project-story.html?project=${slug}"><img src="${p.cardImage}" alt="${p.cardTitle}"/><h3>${p.cardTitle}</h3></a><p>Illustrative project · Kangra</p></article>`).join('')}</div></div></section>`); }

function projectStory(){
  const slug=new URLSearchParams(window.location.search).get('project') || 'bedroom-fitted-storage';
  const p=projectStories[slug] || projectStories['bedroom-fitted-storage'];
  return shell(hero({eyebrow:p.eyebrow,title:p.title,copy:p.copy,image:p.heroImage})+`<section class="page-section"><div class="container"><a class="story-back" href="projects.html">← Back to all projects</a><div class="story-images"><figure><img src="${p.beforeImage}" alt="${p.beforeAlt}"/><figcaption>Before</figcaption></figure><figure><img src="${p.afterImage}" alt="${p.afterAlt}"/><figcaption>After</figcaption></figure></div><p class="story-note">Matched-view concept visualisation showing the same space before and after the proposed design work.</p><div class="story-facts"><article><h3>The problem</h3><p>${p.problem}</p></article><article><h3>Our approach</h3><p>${p.approach}</p></article><article><h3>Materials</h3><p>${p.materials}</p></article><article><h3>The result</h3><p>${p.result}</p></article></div></div></section>`+cta());
}

const adviceCards=[
  [A+'curtains-room.png','Curtains or blinds: Which suits your room?','Compare light control, privacy, maintenance and style.','guide-curtains-vs-blinds.html'],
  [A+'curtains-room.png','Privacy without losing natural light','Layered solutions for bright rooms that still feel private.','guide-privacy-natural-light.html'],
  [A+'wardrobe-room.png','Choosing wardrobes for small bedrooms','Plan storage, circulation and door clearances carefully.','guide-small-bedroom-wardrobes.html'],
  [A+'wardrobe-room.png','Hinged versus sliding wardrobe doors','Understand space, access, maintenance and cost trade-offs.','guide-hinged-vs-sliding.html'],
  [A+'full-home-room.png','Understanding an interior quotation','Know what is included, excluded and still provisional.','guide-interior-quotation.html'],
  [A+'full-home-room.png','Before paying an installer advance','Agree the scope, materials, payment stages and timeline first.','guide-before-paying-advance.html'],
  [A+'damp-wall.png','Seepage or damp walls? Find the cause first','Why moisture diagnosis must come before repainting or covering.','guide-damp-walls.html']
];

function advice(){ return shell(hero({eyebrow:'Home Advice & Guides',title:'Practical answers for<br>Indian homes.',copy:'Clear guidance for common decisions about curtains, privacy, storage, quotations, installation and damp walls.',image:A+'curtains-room.png'})+`<section class="page-section"><div class="container"><h2>Browse all guides</h2><p class="section-intro">Start with the problem you are trying to solve. Each guide explains the options, trade-offs and useful next steps.</p><div class="content-grid">${adviceCards.map(x=>imgCard(x[0],x[1],x[2],x[3],'Read guide')).join('')}</div></div></section>`); }

const articleData={
  curtains:{title:'Curtains or blinds:<br>which suits your room?',intro:'The right choice depends on how you use the room, the amount of sunlight, the privacy you need and the look you prefer.',image:A+'curtains-room.png',takeaway:'Choose around the room’s practical problem first. Style becomes easier once privacy, glare, cleaning and daily operation are clear.',steps:[['Start with the room problem','Note whether your priority is privacy, glare control, darkness for sleep, heat reduction, easy cleaning or a softer decorative finish.'],['When curtains work well','Curtains suit bedrooms and living rooms where softness, acoustic comfort, layering and full-height visual impact matter.'],['When blinds work well','Blinds suit compact windows, work areas and rooms where precise light control or a cleaner visual line is useful.'],['Consider maintenance','Curtains may need periodic washing or dry cleaning. Blinds require regular dusting and accessible operating mechanisms.'],['Combine when necessary','A sheer curtain with a blackout layer, or a blind with decorative curtains, can solve privacy and light-control needs together.']]},
  privacy:{title:'Privacy without losing<br>natural light',intro:'A bright home does not need to feel exposed. Layering and the right fabric openness can protect privacy while keeping daylight.',image:A+'curtains-room.png',takeaway:'Daytime privacy and night-time privacy are different. Plan both conditions before choosing a sheer fabric or blind.',steps:[['Observe the window at different times','Check visibility from outside in the morning, afternoon and after lights are switched on at night.'],['Use sheers for daytime diffusion','Well-chosen sheers soften harsh sunlight and reduce direct views while still allowing the room to feel bright.'],['Add a private evening layer','At night, illuminated interiors can be visible through sheers. Add lined curtains, blackout curtains or an opaque blind.'],['Control glare without closing the room','Light-filtering blinds, adjustable slats and layered curtains can reduce glare on televisions and work surfaces.'],['Match the solution to window orientation','Strong west-facing sun may need denser light control than a shaded north-facing opening.']]},
  smallWardrobes:{title:'Choosing wardrobes<br>for small bedrooms',intro:'In a compact bedroom, wardrobe size is only part of the decision. Door movement, walking space and internal organisation matter just as much.',image:A+'wardrobe-room.png',takeaway:'Measure the usable room after accounting for the bed, bedside movement, switches, windows and door swings.',steps:[['Map the circulation path','Keep a comfortable route from the room entrance to the bed, wardrobe and windows.'],['Use the full height carefully','Overhead storage can help with occasional items, while daily-use shelves and rails should remain easy to reach.'],['Choose the right door system','Sliding doors save opening clearance. Hinged doors offer wider access and simpler internal fittings where space permits.'],['Plan internal zones around real belongings','Count hanging garments, folded clothes, shoes, luggage and accessories before dividing the wardrobe.'],['Keep the finish visually calm','Light finishes, fewer external breaks and restrained handles can make a large storage unit feel quieter in a small room.']]},
  hingedSliding:{title:'Hinged versus sliding<br>wardrobe doors',intro:'Both systems can work well. The better choice depends on room clearance, wardrobe width, access preferences, hardware and maintenance.',image:A+'wardrobe-room.png',takeaway:'Do not choose sliding doors only because the room is small. Check internal access, track quality and the exact furniture clearance first.',steps:[['Compare opening clearance','Hinged shutters need clear space in front. Sliding shutters remain within the wardrobe footprint.'],['Compare access','Hinged doors can expose the full wardrobe at once. Sliding systems usually keep one section covered.'],['Review hardware and maintenance','Hinges are straightforward to adjust. Sliding tracks and rollers need good-quality hardware and occasional cleaning.'],['Consider mirrors and accessories','Full-height mirrors and door-mounted fittings may influence shutter weight and the preferred mechanism.'],['Price the complete system','Compare shutters, internal divisions, tracks or hinges, handles, installation and future servicing rather than only the panel cost.']]},
  quotation:{title:'Understanding an interior<br>quotation and its exclusions',intro:'A clear quotation should help you understand what is being supplied, how quantities are calculated and which costs may still change.',image:A+'full-home-room.png',takeaway:'Compare quotations line by line. A lower total is difficult to judge when scope, brands, quantities or exclusions are unclear.',steps:[['Check the scope room by room','Confirm exactly which rooms, units and activities are included.'],['Look for specifications','Materials, brands, finishes, hardware and thicknesses should be described clearly enough to compare.'],['Understand quantities and rates','Check whether pricing is lump sum, per square foot, per running foot or based on measured quantities.'],['Read every exclusion','Civil work, electrical changes, plumbing, painting, transport, taxes, removal and repairs may be separate.'],['Clarify provisional items','Site conditions, final measurements and selections can change the final cost. Ask how those changes will be approved.']]},
  advance:{title:'What to agree before<br>paying an installer advance',intro:'An advance should follow a shared understanding of the work, materials, price, timeline and responsibilities.',image:A+'full-home-room.png',takeaway:'Keep the agreed scope, payment stages and material specifications in writing before transferring an advance.',steps:[['Confirm the written scope','List the rooms, items, quantities, finishes and installation activities included.'],['Approve materials and samples','Record brands, colours, fabrics, hardware and acceptable alternatives before procurement.'],['Agree payment milestones','Link later payments to measurable stages such as material approval, delivery, installation and handover.'],['Set a realistic timeline','Document dependencies, site-readiness requirements and how delays or changes will be communicated.'],['Record change and cancellation rules','Agree how additional work, refunds, cancellations, warranties and installation concerns will be handled.']]},
  damp:{title:'Seepage or damp walls?<br>Understand the cause first.',intro:'Visible damp, stains or peeling paint can signal a moisture problem. Identify and address the source before repainting or covering the wall.',image:A+'damp-wall.png',takeaway:'A cosmetic finish can hide symptoms briefly, but trapped moisture may damage the new surface and nearby materials.',steps:[['Recognise the symptoms','Look for damp patches, stains, peeling paint or wallpaper, musty smells, powdery deposits and recurring mould.'],['Consider possible sources','Rain penetration, plumbing leaks, rising moisture, roof or balcony failure and condensation can create similar symptoms.'],['Observe the pattern','Note whether the patch changes after rain, plumbing use, cold weather or periods when the room stays closed.'],['Fix and dry before finishing','Repair the source, allow sufficient drying time and confirm the wall condition before repainting or installing panels.'],['Seek specialist diagnosis when needed','If the source is unclear, recurring or structural, consult an appropriate waterproofing, plumbing or building specialist.']]}
};

function articleGuide(key){ const a=articleData[key]; const related=adviceCards.filter(x=>!x[1].startsWith(a.title.split('<br>')[0])).slice(0,3); return shell(`<section class="article-page-intro"><div class="container"><article class="article-cover-card"><img src="${a.image}" alt="${a.title.replace('<br>',' ')}"/><div class="article-cover-copy"><p class="eyebrow">Home Advice &amp; Guides</p><h1>${a.title}</h1><p>${a.intro}</p></div></article></div></section><section class="article-body"><div class="container"><div class="article-surface"><div class="guide-layout"><div><div class="guide-list">${a.steps.map(x=>`<article><div><h3>${x[0]}</h3><p>${x[1]}</p></div></article>`).join('')}</div><div class="notice" style="margin-top:28px"><strong>Planning note:</strong> These guides provide general information. Final recommendations should account for actual measurements, site conditions and confirmed product specifications.</div></div><aside class="side-panel"><h3>Key takeaway</h3><p>${a.takeaway}</p><a class="button" href="start-project.html">Plan Your Project →</a></aside></div></div></div></section><section class="page-section tint"><div class="container"><h2>Related guides</h2><div class="content-grid">${related.map(x=>imgCard(x[0],x[1],x[2],x[3],'Read guide')).join('')}</div></div></section>`); }

function guide(){ return articleGuide('damp'); }

function about(){ return shell(hero({eyebrow:'About AK Interiors',title:'Helping you create<br>a home you’ll love.',copy:'Friendly, personal service from initial ideas to final installation, focused on quality, practicality and attention to detail.',image:A+'hero-living-room.png'})+`<section class="page-section"><div class="container"><div class="content-grid"><article class="content-card"><div class="content-card-body"><span class="line-icon">◇</span><h3>Our approach</h3><p>We take time to understand your home and how you live, then recommend solutions that suit your needs.</p></div></article><article class="content-card"><div class="content-card-body"><span class="line-icon">⌖</span><h3>Local service</h3><p>Based locally, we serve homeowners across Kangra and surrounding areas of Himachal Pradesh.</p></div></article><article class="content-card"><div class="content-card-body"><span class="line-icon">✓</span><h3>Practical quality</h3><p>Clear choices, coordinated installation and thoughtful final checks.</p></div></article></div></div></section>`+cta()); }

function faqs(){ const qs=[['Estimates & quotations','Information about estimates, what is included and how long they are valid.'],['Home visits','When we arrange home visits and what to expect.'],['Materials & products','Questions about fabrics, finishes, sourcing and care.'],['Installation','How installation works, timescales and preparation.'],['Aftercare & support','Information on guarantees, maintenance and getting in touch.']]; return shell(hero({eyebrow:'FAQs',title:'Frequently asked questions',copy:'Quick answers to common questions.',image:A+'full-home-room.png'})+`<section class="page-section"><div class="container"><div class="faq-list">${qs.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]} Contact us if you need advice specific to your project.</p></details>`).join('')}</div></div></section>`); }

function startProject(){ return shell(`<section class="form-page"><div class="container"><div class="form-shell"><div><p class="eyebrow">Start Your Project</p><h1>Tell us about your home.</h1><p>Share your requirements and we’ll contact you to discuss the next steps. Submission does not automatically confirm a visit.</p><div class="upload-box">⇧<br/>Project photos (optional)<br/><small>Drag and drop or click to upload</small></div></div><form class="form-grid" data-demo-form data-success="enquiry-received.html">${field('Service','<select><option>Select a service</option><option>Curtains & Blinds</option><option>Wardrobes & Storage</option><option>Full Home Interiors</option></select>')}${field('Location','<input placeholder="Town or area" required/>')}${field('Budget range','<select><option>Select a budget range</option><option>Under ₹2 lakh</option><option>₹2–5 lakh</option><option>₹5 lakh+</option></select>')}${field('Preferred timing','<select><option>Select timing</option><option>Within 3 months</option><option>3–6 months</option><option>Flexible</option></select>')}${field('Name','<input placeholder="Your name" required/>')}${field('Email','<input type="email" placeholder="you@example.com" required/>')}<label class="field span-two">Tell us about your project<textarea placeholder="Your rooms, needs and priorities"></textarea></label><label class="span-two"><input type="checkbox" required/> I agree to the Privacy Policy and Terms &amp; Consultation Policy.</label><button class="button span-two" type="submit">Submit Enquiry →</button></form></div></div></section>`); }

function received(){ return shell(`<section class="form-page"><div class="container"><div class="success-panel"><span class="success-check">✓</span><h1>Your enquiry is ready for review</h1><p>Thank you for getting in touch. We’ve received your details and will review your enquiry.</p></div><div class="next-steps"><article><span class="step-no">1</span><h3>We review your enquiry</h3><p>Our team looks at your project details and photos.</p></article><article><span class="step-no">2</span><h3>Phone discussion</h3><p>We’ll get in touch for a quick call about your project.</p></article><article><span class="step-no">3</span><h3>If suitable, a visit</h3><p>If the project is a good fit, we arrange a suitable time to visit.</p></article></div><div class="notice blue"><strong>Please note:</strong> A visit is not automatically confirmed. All enquiries are reviewed and discussed first.</div></div></section>`); }

function contact(){ return shell(`<section class="form-page"><div class="container contact-grid"><article class="contact-panel"><p class="eyebrow">Contact & Service Areas</p><h1>Get in Touch</h1><p>We’d love to hear about your project. Reach out using the options below or send us a service-area enquiry.</p><a class="button" href="start-project.html">Request a Call</a> <a class="button" href="start-project.html">Start an Enquiry</a><hr style="margin:28px 0;border:0;border-top:1px solid #ddd"/>${field('Service Area Enquiry','<input placeholder="Town or area"/>')}<a class="button" href="start-project.html">Send Enquiry →</a></article><aside class="service-area"><div><h2>Our Service Areas</h2><h3>Kangra<br/>Himachal Pradesh</h3><p>We undertake projects across Kangra and surrounding areas.</p></div></aside></div></section>`); }

const policyText={privacy:[['Data we collect','We may collect your name, contact details, project information, photos and other details you provide through our website or during conversations.'],['Purpose','We use your information to respond to enquiries, discuss and plan your project, arrange visits where suitable and provide our services.'],['Retention','We keep your information only for as long as necessary to fulfil these purposes or as required by law.'],['Your choices','You can request access, updates or deletion of your information by contacting us.']],terms:[['Estimates and limitations','Any estimate or initial advice is based on the information available at the time. Final scope, specification and costs are confirmed after consultation and site review where appropriate.'],['Consultation booking','After reviewing your enquiry, we contact you to discuss your project. A visit is not automatically confirmed.'],['Scope approval','Work proceeds once the scope, design, quotation and project details have been agreed in writing.'],['Changes','Changes to scope, materials, timing or cost require written approval before work continues.']]};
function policy(kind){ const title=kind==='privacy'?'Privacy Policy':'Terms & Consultation Policy'; return shell(`<section class="form-page"><div class="container policy"><p class="eyebrow">AK Interiors</p><h1>${title}</h1><p>This readable draft explains how we handle ${kind==='privacy'?'your personal information':'enquiries, consultations and project scope'}.</p>${policyText[kind].map((x,i)=>`<article><h2>${i+1}. ${x[0]}</h2><p>${x[1]}</p></article>`).join('')}</div></section>`); }

function dashboard(){ return dashboardShell(`<div class="dashboard-head"><h1>Enquiries</h1><a class="button" href="start-project.html">+ New Enquiry</a></div><div class="filters">${['Status','Service','Location','Date range'].map(x=>field(x,'<select><option>All</option></select>')).join('')}</div><div class="data-card"><table class="data-table"><thead><tr><th>ID</th><th>Service</th><th>Location</th><th>Budget</th><th>Timing</th><th>Status</th></tr></thead><tbody>${[['ENQ-001','Curtains & Blinds','Kangra','Mid range','3–6 months','New'],['ENQ-002','Wardrobes','Dharamshala','Not specified','Flexible','In review'],['ENQ-003','Full Home','Kangra','Mid to high','1–3 months','Contacted'],['ENQ-004','New build','Palampur','Not specified','Flexible','New'],['ENQ-005','Wardrobes','Kangra','Low to mid','3–6 months','In review']].map(r=>`<tr>${r.map((c,i)=>i===5?`<td><span class="status ${c==='In review'?'review':c==='Contacted'?'contacted':''}">${c}</span></td>`:`<td>${i===0?`<a href="enquiry-detail.html">${c}</a>`:c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`); }
function dashboardShell(content){ return `<main class="dashboard-shell"><aside class="dashboard-sidebar"><div class="dashboard-logo">AK INTERIORS</div><nav class="dashboard-nav"><a href="index.html">⌂ Overview</a><a class="active" href="enquiry-dashboard.html">✉ Enquiries</a><a href="#">▣ Visits</a></nav></aside><section class="dashboard-main">${content}</section></main>`; }
function detail(){ return dashboardShell(`<div class="dashboard-head"><div><a href="enquiry-dashboard.html">← Back to enquiries</a><h1>ENQ-002 <span class="status review">In review</span></h1></div></div><div class="detail-grid"><article class="detail-card"><h2>Service brief</h2><p>Wardrobes for an existing home. The customer is looking for a modern, functional design with natural materials.</p><dl><dt>Location</dt><dd>Dharamshala</dd><dt>Budget range</dt><dd>Mid to high</dd><dt>Preferred timing</dt><dd>3–6 months</dd></dl></article><article class="detail-card"><h2>Project photos</h2><div class="photo-strip"><img src="${A}wardrobe-room.png" alt="Project"/><img src="${A}curtains-room.png" alt="Project"/><img src="${A}full-home-room.png" alt="Project"/></div></article><article class="detail-card"><h2>Notes</h2><p>Client prefers an open, organised layout and will discuss material options and sustainability during the call.</p>${field('Review status','<select><option>In review</option><option>Contacted</option><option>Ready for visit</option></select>')}</article><article class="detail-card"><h2>Actions</h2><div style="display:flex;flex-wrap:wrap;gap:10px"><button class="button secondary">Request info</button><button class="button secondary">Arrange call</button><button class="button">Ready for visit</button></div></article></div>`); }

const renderers={services:servicesOverview,curtains:()=>servicePage('curtains'),wardrobes:()=>servicePage('wardrobes'),kitchens:()=>servicePage('kitchens'),'full-home':()=>servicePage('full-home'),'other-services':()=>servicePage('other-services'),materials:()=>servicePage('materials'),'plan-home':planHome,'curtains-planner':curtainsPlanner,'wardrobe-planner':wardrobePlanner,'project-planner':projectPlanner,estimate,commitment,journey,projects,'project-story':projectStory,advice,guide,'article-curtains':()=>articleGuide('curtains'),'article-privacy':()=>articleGuide('privacy'),'article-small-wardrobes':()=>articleGuide('smallWardrobes'),'article-hinged-sliding':()=>articleGuide('hingedSliding'),'article-quotation':()=>articleGuide('quotation'),'article-advance':()=>articleGuide('advance'),about,faqs,'start-project':startProject,received,contact,privacy:()=>policy('privacy'),terms:()=>policy('terms'),dashboard,detail};
const page=document.body.dataset.page;
if(page==='project-story'){
  const storySlug=new URLSearchParams(window.location.search).get('project') || 'bedroom-fitted-storage';
  document.title=`${(projectStories[storySlug] || projectStories['bedroom-fitted-storage']).cardTitle} | AK Interiors`;
}else{
  document.title=`${pageNames[page]||'AK Interiors'} | AK Interiors`;
}
document.querySelector('#app').innerHTML=(renderers[page]||servicesOverview)();

const menuButton=document.querySelector('.menu-toggle');
const navigation=document.querySelector('.main-nav');
if(menuButton&&navigation){menuButton.addEventListener('click',()=>{const open=navigation.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));});}
document.querySelectorAll('[data-demo-form]').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();window.location.href=form.dataset.success;}));
document.querySelectorAll('.project-filters .pill').forEach(pill=>pill.addEventListener('click',()=>{
  const selected=pill.dataset.filter;
  document.querySelectorAll('.project-filters .pill').forEach(button=>{
    const active=button===pill;
    button.classList.toggle('active',active);
    button.setAttribute('aria-pressed',String(active));
  });
  document.querySelectorAll('.project-card').forEach(card=>{
    card.hidden=selected!=='all'&&card.dataset.category!==selected;
  });
}));
